---
# see https://github.com/Shopify/tapioca?tab=readme-ov-file#configuration
gem:
  exclude:
    # These conflict with the rbi files provided by sorbet:
    - json
    - msgpack
    # These aren't needed:
    - byebug
    - coderay
    - commander
    - diff-lcs
    - docile
    - hana
    - highline
    - language_server-protocol
    - netrc
    - parallel
    - public_suffix
    - racc
    - rexml
    - rspec-github
    - rspec-mocks
    - rspec-retry
    - rspec
    - rspec_junit_formatter
    - rubocop-capybara
    - rubocop-factory_bot
    - rubocop-md
    - rubocop-performance
    - rubocop-rspec
    - rubocop-rspec_rails
    - rubocop-sorbet
    - ruby-prof
    - simplecov_json_formatter
    - simpleidn
    - unf
    - unf_ext
    - unicode-display_width
    - yard-sorbet
  prerequire: sorbet/tapioca/prerequire.rb
