name: Update Sorbet files

on:
  push:
    paths:
      - .github/workflows/sorbet.yml
    branches-ignore:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tapioca:
    if: github.repository == 'Homebrew/brew'
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: BrewTestBot

      - name: Set up commit signing
        uses: Homebrew/actions/setup-commit-signing@master
        with:
          signing_key: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY }}

      - name: Update RBI files
        id: update
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN }}
          HOMEBREW_GPG_PASSPHRASE: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY_PASSPHRASE }}
        run: |
          git fetch origin

          BRANCH="sorbet-files-update"
          echo "::set-output name=branch::${BRANCH}"

          if git ls-remote --exit-code --heads origin "${BRANCH}"
          then
            git checkout "${BRANCH}"
            git reset --hard origin/master
          else
            git checkout --no-track -B "${BRANCH}" origin/master
          fi

          if brew typecheck --update --fail-if-not-changed
          then
            git add "${GITHUB_WORKSPACE}/Library/Homebrew/sorbet"
            git commit -m "sorbet: Update RBI files." \
                       -m "Autogenerated by the [sorbet](https://github.com/Homebrew/brew/blob/master/.github/workflows/sorbet.yml) workflow."
            echo "::set-output name=committed::true"
            PULL_REQUEST_STATE="$(gh pr view --json=state | jq -r ".state")"
            if [[ "${PULL_REQUEST_STATE}" != "OPEN" ]]
            then
              echo "::set-output name=pull_request::true"
            fi
          fi

      - name: Push commits
        if: steps.update.outputs.committed == 'true'
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN }}
          branch: ${{ steps.update.outputs.branch }}
          force: true
          origin_branch: "master"

      - name: Open a pull request
        if: steps.update.outputs.pull_request == 'true'
        run: hub pull-request --no-edit
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN }}
