name: Update license data
on:
  pull_request:
    paths:
      - .github/workflows/spdx.yml
  schedule:
    - cron: '0 */12 * * *'
jobs:
  spdx:
    if: github.repository == 'Homebrew/brew'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: BrewTestBot

      - name: Update license data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd "$GITHUB_WORKSPACE/Library/Homebrew"
          if brew update-license-data --commit --fail-if-not-changed; then
            SPDX_VERSION=$(jq -er .licenseListVersion data/spdx.json)
            if ! git ls-remote --exit-code --heads origin "spdx-$SPDX_VERSION"; then
              git checkout -b "spdx-$SPDX_VERSION"
              git push origin "spdx-$SPDX_VERSION"
              hub pull-request -m "$(git log -1 --format='%s')"
            fi
          fi
